name: Scheduled Node.js Run

on:
  schedule:
    # Lên lịch chạy lúc 8:00 và 17:00 (giờ UTC)
    - cron: '0 1 * * 1-5'
    - cron: '30 10 * * 1-5'

jobs:
  run-nodejs:
    runs-on: ubuntu-latest

    steps:
      - name: Check current time
        run: date -u

      # Checkout mã nguồn từ repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Thiết lập Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Thay bằng phiên bản Node.js của bạn

      - name: create env file
        run: |
          touch .env
          echo EMAIL=${{ secrets.EMAIL }} >> .env
          echo PASSWORD=${{ secrets.PASSWORD }} >> .env

      # Cài đặt dependencies
      - name: Install dependencies
        run: npm install

      # Chạy dự án
      - name: Run project
        run: npm run start
