name: Delayed Test Workflow

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check current time
        run: date -u

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: create env file
        run: |
          touch .env
          echo EMAIL=${{ secrets.EMAIL }} >> .env
          echo PASSWORD=${{ secrets.PASSWORD }} >> .env

      # Cài đặt dependencies
      - name: Install dependencies
        run: npm install

      # Chạy dự án
      - name: Run project
        run: npm run start
